### ISSUE TITLE
Trail of 0s after editing

### ISSUE THREAD

**Issue by nmaggioni** [cxreg/smartcd#19]
After editing a script with 'smartcd edit enter' or 'smartcd edit leave', the terminal starts to output 0s!
Zero, newline, zero, newline, never stopping... I must CTRL^C out of it, and changes to the script are not saved.
I'm running Ubuntu 13.10 and zsh with the last oh-my-zsh version.

**Comment by daotoad** [comment]
No feedback, couldn't repro.
