### ISSUE TITLE
Overriding the `cd` function

### ISSUE THREAD

**Issue by jackfranklin** [cxreg/smartcd#37]
Just installed smartcd on OS X using ZSH and installing smartcd has led to my `cd` function being changed:

```
> which cd         
cd () {
    smartcd cd "$@"
}
```

However, I usually use my own custom `cd` function:

```
cd () {
  builtin cd "$*"
  ls
}
```

Is there a way I can keep my custom behaviour but add smartcd to it as well?

Many thanks,

Jack

**Comment by daotoad** [comment]
I don't know much about zsh, but I can tell you that as part of smartcd's configuration process you are asked if you want to wrap cd, and you can decline.  If you're running zsh, it should also ask if you want to use the zsh chpwd hooks.

You can either edit `.smartcd_config` manually or run `smartcd config` to alter the settings.

Based on my reading of the configuration code, you want to delete these lines:

    smartcd setup cd
    smartcd setup pushd
    smartcd setup prompt-hook

And replace them with this line:

    smartcd setup chpwd
