### ISSUE TITLE
.bashrc prompt ignored

### ISSUE THREAD

**Issue by nkh** [cxreg/smartcd#42]
with the following in the .smartcd_config:

smartcd setup prompt-hook

When opening creating a new session, the original prompt is replaced; ignoring my PROMPT_COMMAND.

I'd like that to be used till I override it for a specific directory.

**Comment by daotoad** [comment]
I've been able to confirm that $PROMPT_COMMAND gets set to `_smartcd_prompt_hook` and that `_smartcd_original_prompt_command` is getting set  to `:`.

```
export PROMPT_COMMAND='echo "I am the prompt command $@"'
echo $PROMPT_COMMAND
smartcd setup prompt-hook
echo $PROMPT_COMMAND
echo $_smartcd_original_prompt_command
```

I'm not 100% sure what the desired behavior of the prompt hooks are, so I am going to stop here for now.
