### ISSUE TITLE
History helper documentation

### ISSUE THREAD

**Issue by nkh** [cxreg/smartcd#43]
Before smartcd my system was setup to keep a history per directory. The documentation hints for a similar functionality but is confusing me at best.

**Comment by daotoad** [comment]
Just put the commands in your enter script:

    # Put shared bash history at the start of the history
    # You can have as many of these as you want.
    smartcd helper run history also-read ~/.bash_history

    # Read and write directory specific history 
    smartcd helper run history localize __PATH__/.history

    # Force writing to history file each time a new prompt is shown
    smartcd helper run history prompt-append

    # Force reading from history file each time a new prompt is shown
    smartcd helper run history prompt-reload

The last two options are to make it so history is shared more effectively between multiple terminal windows working in the same directory.

**Comment by daotoad** [comment]
Months with no reply to my response.  I am closing this issue.
