### ISSUE TITLE
Question on new tabs and smartcd

### ISSUE THREAD

**Issue by jonasbn** [cxreg/smartcd#48]
I am using **smartcd** in combination with **liquid prompt** and it works like a charm, one thing I have not been able to figure out is how to enable **smartcd** for new tabs.

I am not doing anything fancy, I just like to prefix the prompts in some of my working directories using **liquid prompt**'s `prompt_tag`

`prompt_tag "\e[1;7m SUPERPROJECT \e[m"`

What I currently am observing for new tabs is the following:

`smartcd: running /Users/jonasbn/.smartcd/scripts/Users/jonasbn/develop/git-dkhm/project/bash_enter
-bash: prompt_tag: command not found`

Have anybody solved the issue with new tabs of have any pointers before I did into the **smartcd** source code.

**Liquid Prompt**: https://github.com/nojhan/liquidprompt

**Comment by daotoad** [comment]
I don't use liquid prompt (but it looks intersting).  It seems like the issue is that smartcd is executing its on enter handlers before liquid prompt is loaded.  

Try loading liquid prompt before you load smartcd in your bashrc.

**Comment by jonasbn** [comment]
Thanks it works like a charm :-)
