### ISSUE TITLE
It has not been maintained for a while

### ISSUE THREAD

**Issue by b4b4r07** [cxreg/smartcd#49]
Similar products:

- https://github.com/b4b4r07/enhancd
- https://github.com/shyiko/commacd
- https://github.com/wting/autojump
- https://github.com/MikeDacre/cdbk
- https://github.com/mfaerevaag/wd
- https://github.com/Tarrasch/zsh-bd
- https://github.com/vigneshwaranr/bd
- https://github.com/mollifier/cd-bookmark
- https://github.com/willghatch/zsh-cdr

**Comment by jcrben** [comment]
Think you commented on the wrong project. This isn't an autojump type of thing - it's more `autoenv`, but it seems like the most powerful / flexible one out there.

**Comment by daotoad** [comment]
I don't have time to lavish on the project, and Dave is really rather busy as well.  But the project is maintained.  I don't use or know much about zsh, so I have been slower to get things updated there.  Also, it's taken me a while to understand the code  enough to take some of the larger pmerge requests.
