### ISSUE TITLE
Hide "smartcd: running..." when changing directories

### ISSUE THREAD

**Issue by Benjamin-Lee** [cxreg/smartcd#61]
Currently, when changing directories, I get a message like this:

```smartcd: running /Users/BenjaminLee/.smartcd/scripts/Users/BenjaminLee/Python/bash_leave```

This can be annoying, especially since it's deactivating a virtualenv which already shows that it was deactivated.  It there a way to suppress the notification?

**Comment by cxreg** [comment]
yes, you can disable these by setting `SMARTCD_QUIET` either in your environment or in the smartcd config file

**Comment by Benjamin-Lee** [comment]
Got it! Thanks!

**Comment by jonasbn** [comment]
I remember enabling this, but I could remember how. Perhaps this should go into the documentation?

**Comment by daotoad** [comment]
Merged PR62.
